name = "voidumesha.me"
type = "webpack"
account_id = "umesharukshan2000@gmail.com"
workers_dev = true

[site]
bucket = "./img"
entry-point = "App.js"
routes = [
    { pattern = "/api/*", script = "api/index.js" },
    { pattern = "/*", script = "worker.js" }
]

[build]
command = "npm run build"